CREATE TABLESPACE ProyectoBD2_Final
DATAFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\ProyectoBD2_Final.DBF'
SIZE 128M
AUTOEXTEND ON NEXT 64M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TempProyectoBD2_Final
TEMPFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\TempProyectoBD2_Final.DBF'
SIZE 128M

CREATE USER proyectoFinal_user IDENTIFIED BY proyectoFinal
DEFAULT TABLESPACE ProyectoBD2_Final
TEMPORARY TABLESPACE TempProyectoBD2_Final
QUOTA UNLIMITED ON ProyectoBD2_Final;

-- ------------------------------------------------------------------------------------------------------
-- --------------------------CREACION DE LAS TABLAS------------------------------------------------------

CREATE TABLE Tipo_donacion (
    tipo_donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Organizacion (
    organizacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(15),
    email VARCHAR2(100),
    estado VARCHAR2(20),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Voluntario (
    voluntario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(15) UNIQUE NOT NULL,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE,
    email VARCHAR2(100),
    telefono VARCHAR2(15),
    direccion VARCHAR2(255),
    estado_civil VARCHAR2(30),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Categoria (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Actividad (
    actividad_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id NUMBER NOT NULL,
    categoria_id NUMBER NOT NULL,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(255),
    ubicacion VARCHAR2(255),
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR2(20),
    CONSTRAINT fk_actividad_org FOREIGN KEY (organizacion_id)
        REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_actividad_categoria FOREIGN KEY (categoria_id)
        REFERENCES Categoria (categoria_id)
);

CREATE TABLE Donacion (
    donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    organizacion_id NUMBER NOT NULL,
    tipo_donacion_id NUMBER NOT NULL,
    cantidad NUMBER(10,2),
    fecha DATE DEFAULT SYSDATE,
    calificacion NUMBER(3),
    CONSTRAINT fk_donacion_vol FOREIGN KEY (voluntario_id)
        REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_donacion_org FOREIGN KEY (organizacion_id)
        REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_donacion_tipo FOREIGN KEY (tipo_donacion_id)
        REFERENCES Tipo_donacion (tipo_donacion_id)
);

CREATE TABLE Asignacion_actividades (
    asignacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    actividad_id NUMBER NOT NULL,
    fecha DATE DEFAULT SYSDATE,
    estado VARCHAR2(20),
    calificacion NUMBER(3),
    CONSTRAINT fk_asignacion_vol FOREIGN KEY (voluntario_id)
        REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_asignacion_act FOREIGN KEY (actividad_id)
        REFERENCES Actividad (actividad_id)
);

select * from Categoria;

-- Sincronizar Contadores
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(tipo_donacion_id), 0) + 1 INTO v_max FROM Tipo_donacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Tipo_donacion MODIFY tipo_donacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(organizacion_id), 0) + 1 INTO v_max FROM Organizacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Organizacion MODIFY organizacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(voluntario_id), 0) + 1 INTO v_max FROM Voluntario;
    EXECUTE IMMEDIATE 'ALTER TABLE Voluntario MODIFY voluntario_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(categoria_id), 0) + 1 INTO v_max FROM Categoria;
    EXECUTE IMMEDIATE 'ALTER TABLE Categoria MODIFY categoria_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(actividad_id), 0) + 1 INTO v_max FROM Actividad;
    EXECUTE IMMEDIATE 'ALTER TABLE Actividad MODIFY actividad_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(donacion_id), 0) + 1 INTO v_max FROM Donacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Donacion MODIFY donacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(asignacion_id), 0) + 1 INTO v_max FROM Asignacion_actividades;
    EXECUTE IMMEDIATE 'ALTER TABLE Asignacion_actividades MODIFY asignacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/
-- ------------------------------------------------------------------------------------------------------
-- -------------Scripts de Creación de Objetos de Programación almacenados-------------------------------

--Procedimiento almacenado: Registrar nueva donación
--Automatiza el proceso de insertar donaciones nuevas, asegurando que solo se necesiten los parámetros principales (el sistema añade fecha y otros datos automáticamente).
CREATE OR REPLACE PROCEDURE RegistrarDonacion (
    p_voluntario_id     IN NUMBER,
    p_organizacion_id   IN NUMBER,
    p_tipo_donacion_id  IN NUMBER,
    p_cantidad          IN NUMBER,
    p_calificacion      IN NUMBER DEFAULT NULL
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar existencia del voluntario
    SELECT COUNT(*) INTO v_exists FROM Voluntario WHERE voluntario_id = p_voluntario_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El voluntario no existe.');
    END IF;

    -- Verificar existencia de la organización
    SELECT COUNT(*) INTO v_exists FROM Organizacion WHERE organizacion_id = p_organizacion_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La organización no existe.');
    END IF;

    -- Verificar existencia del tipo de donación
    SELECT COUNT(*) INTO v_exists FROM Tipo_donacion WHERE tipo_donacion_id = p_tipo_donacion_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El tipo de donación no existe.');
    END IF;

    -- Inserción de la donación
    INSERT INTO Donacion (
        voluntario_id,
        organizacion_id,
        tipo_donacion_id,
        cantidad,
        fecha,
        calificacion
    ) VALUES (
        p_voluntario_id,
        p_organizacion_id,
        p_tipo_donacion_id,
        p_cantidad,
        SYSDATE,      
        p_calificacion
    );

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Donación registrada correctamente.');
END;
/

SET SERVEROUTPUT ON;

BEGIN
    RegistrarDonacion( p_voluntario_id => 1, p_organizacion_id => 1, p_tipo_donacion_id => 1, p_cantidad => 250.75, p_calificacion => 95);
END;
/

--Función almacenada: Calcular total donado por voluntario
--Devuelve el monto total donado por un voluntario. Puede usarse en reportes o consultas de desempeño de voluntarios
CREATE OR REPLACE FUNCTION CalcularTotalDonado (
    p_voluntario_id IN NUMBER
) RETURN NUMBER
IS
    v_total NUMBER := 0;
BEGIN
    -- Calcula la suma total de donaciones realizadas por el voluntario
    SELECT NVL(SUM(cantidad), 0)
    INTO v_total
    FROM Donacion
    WHERE voluntario_id = p_voluntario_id;

    RETURN v_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

SELECT 
    v.voluntario_id,
    v.nombres,
    v.apellidos,
    CalcularTotalDonado(v.voluntario_id) AS total_donado
FROM Voluntario v;


-- Trigger: Actualizar estado de actividad automáticamente
--Actualiza automáticamente el estado de una actividad según sus fechas, evitando errores humanos y manteniendo la consistencia de datos
CREATE OR REPLACE TRIGGER ActualizarEstadoActividad
BEFORE INSERT OR UPDATE ON Actividad
FOR EACH ROW
BEGIN
    IF :NEW.fecha_inicio > SYSDATE THEN
        :NEW.estado := 'Programada';
    ELSIF :NEW.fecha_inicio <= SYSDATE 
       AND (:NEW.fecha_fin IS NULL OR :NEW.fecha_fin > SYSDATE) THEN
        :NEW.estado := 'En curso';
    ELSIF :NEW.fecha_fin <= SYSDATE THEN
        :NEW.estado := 'Finalizada';
    END IF;
END;
/

INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Campaña Escolar', 'Reparto de útiles escolares', 'Cuzco',
        TO_DATE('2025-12-01', 'YYYY-MM-DD'),
        TO_DATE('2025-12-05', 'YYYY-MM-DD'));
INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Donación de Sangre', 'Campaña en hospitales locales', 'Lima',
        SYSDATE - 1,
        SYSDATE + 2);
INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Reforestación 2023', 'Evento ecológico anual', 'Arequipa',
        TO_DATE('2023-01-10', 'YYYY-MM-DD'),
        TO_DATE('2023-01-12', 'YYYY-MM-DD'));
        
select * from Actividad;



-- Vista: Vista de donaciones detalladas
--Facilita las consultas y reportes mostrando toda la información de donaciones en una sola vista sin tener que hacer múltiples joins cada vez

CREATE OR REPLACE VIEW Donaciones_Detalladas AS
SELECT
    d.donacion_id,
    d.fecha AS fecha_donacion,
    d.cantidad,
    d.calificacion AS calificacion_donacion,
    
    v.voluntario_id,
    v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    v.dni,
    v.email AS email_voluntario,
    
    o.organizacion_id,
    o.nombre AS nombre_organizacion,
    o.email AS email_organizacion,
    
    td.tipo_donacion_id,
    td.nombre AS tipo_donacion,
    td.descripcion AS descripcion_tipo_donacion
FROM Donacion d
JOIN Voluntario v ON d.voluntario_id = v.voluntario_id
JOIN Organizacion o ON d.organizacion_id = o.organizacion_id
JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id;


SELECT *
FROM Donaciones_Detalladas
WHERE cantidad > 100
ORDER BY fecha_donacion DESC;

--Paquete PL/SQL: Gestión de voluntarios
--Agrupa operaciones comunes relacionadas con voluntarios (registro y conteo), haciendo más organizada y reutilizable la lógica del sistema
CREATE OR REPLACE PACKAGE Voluntarios_Pkg
AS
    PROCEDURE RegistrarVoluntario(
        p_dni          IN VARCHAR2,
        p_nombres      IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_fecha_nac    IN DATE DEFAULT NULL,
        p_email        IN VARCHAR2 DEFAULT NULL,
        p_telefono     IN VARCHAR2 DEFAULT NULL,
        p_direccion    IN VARCHAR2 DEFAULT NULL,
        p_estado_civil IN VARCHAR2 DEFAULT NULL
    );
    FUNCTION ContarVoluntarios RETURN NUMBER;
END Voluntarios_Pkg;
/
CREATE OR REPLACE PACKAGE BODY Voluntarios_Pkg
AS
    PROCEDURE RegistrarVoluntario(
        p_dni          IN VARCHAR2,
        p_nombres      IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_fecha_nac    IN DATE DEFAULT NULL,
        p_email        IN VARCHAR2 DEFAULT NULL,
        p_telefono     IN VARCHAR2 DEFAULT NULL,
        p_direccion    IN VARCHAR2 DEFAULT NULL,
        p_estado_civil IN VARCHAR2 DEFAULT NULL
    )
    IS
    BEGIN
        INSERT INTO Voluntario (
            dni, nombres, apellidos, fecha_nacimiento,
            email, telefono, direccion, estado_civil, fecha_registro
        )
        VALUES (
            p_dni, p_nombres, p_apellidos, p_fecha_nac,
            p_email, p_telefono, p_direccion, p_estado_civil, SYSDATE
        );
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Voluntario registrado correctamente.');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('Error al registrar voluntario: ' || SQLERRM);
    END RegistrarVoluntario;
    FUNCTION ContarVoluntarios RETURN NUMBER
    IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total FROM Voluntario;
        RETURN v_total;
    END ContarVoluntarios;
END Voluntarios_Pkg;
/



